### ISSUE TITLE
AH00558: apache2: about ServerName

### ISSUE THREAD

**Issue by woshizilong** [andreicon/snipe-it#1]
when i run your docker-compose.yml.
I get error.

```
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
```

 you encountered this error?

**Comment by andreicon** [comment]
That's not really an error, it's actually a warning, so apache should be running in that container and you'd be able to access it on port 80.

To suppress that warning you need to first copy the apache config from inside the container to your local machine, edit it and then mount it as a volume.

**Comment by woshizilong** [comment]
thank you for answer
